apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yaml
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: petclinic
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: petclinic
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yaml
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: petclinic
    spec:
      containers:
        - args:
            - java
            - -Djava.security.egd=file:/dev/./urandom
            - -jar
            - /spring-petclinic.jar
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysqlserver/petclinic
            - name: SERVER_PORT
              value: "8080"
          image: localhost:5000
          name: petclinic
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
